# name: Update Workflows

# on:
#   repository_dispatch:
#     types: [update_workflows]

# permissions:
#   contents: write
#   actions: write

# jobs:
#   update:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: false  # Disable persist-credentials to use PAT
#           fetch-depth: 0

#       - name: Fetch Central Template
#         run: |
#           curl -O https://raw.githubusercontent.com/simehta7/repo1/main/.github/workflows/template.yml

#       - name: Update Workflow Files
#         run: |
#           mkdir -p .github/workflows
#           cp template.yml .github/workflows/manifest1.yml
#           rm template.yml

#       - name: Commit changes
#         run: |
#           git config --local user.email "github-actions[bot]@users.noreply.github.com"
#           git config --local user.name "github-actions[bot]"
#           git add .github/workflows/manifest1.yml
#           git commit -m "Update workflow files from central template" || echo "No changes to commit"

#       - name: Push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#           branch: main


name: Update Workflows

on:
  repository_dispatch:
    types: [update_workflows]

permissions:
  contents: write
  actions: write
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Disable persist-credentials to use PAT
          fetch-depth: 0

      - name: Fetch Workflow Files from Central Repository
        run: |
          curl -O https://raw.githubusercontent.com/simehta7/repo1/main/.github/workflows/template.yml
      - name: Replace Placeholders
        run: |
          # sed -i 's/querybot-airprojects/actual_value_1/g' 01-build-and-deploy.yml
          # sed -i 's/querybot.airprojects.org/actual_value_2/g' 01-build-and-deploy.yml
          # # Add more sed commands for other placeholders and other files if needed

      - name: Update Workflow Files
        run: |
          mkdir -p .github/workflows
          cp template.yml .github/workflows/
          rm template.yml 

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/01-build-and-deploy.yml .github/workflows/02-manual-deploy.yml .github/workflows/03-monthly-patching.yml
          git commit -m "Update workflow files from central repository" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PERSONAL_AACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"
