# # # # # qb2test/.github/workflows/update_workflows.yml
# # # # name: Update Workflows

# # # # on:
# # # #   repository_dispatch:
# # # #     types: [update_workflows]

# # # # permissions:
# # # #   contents: write
# # # #   actions: write

# # # # jobs:
# # # #   update:
# # # #     runs-on: ubuntu-latest

# # # #     steps:
# # # #       - name: Checkout code
# # # #         uses: actions/checkout@v2

# # # #       - name: Fetch Central Template
# # # #         run: |
# # # #           curl -O https://raw.githubusercontent.com/American-Institutes-for-Research/central-workflows/main/.github/workflows/template.yml

# # # #       - name: Update Workflow Files
# # # #         run: |
# # # #           mkdir -p .github/workflows
# # # #           cp template.yml .github/workflows/manifest1.yml
# # # #           rm template.yml

# # # #       - name: Configure Git
# # # #         run: |
# # # #           git config --global user.name "github-actions[bot]"
# # # #           git config --global user.email "github-actions[bot]@users.noreply.github.com"

# # # #       - name: Pull Latest Changes
# # # #         env:
# # # #           PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
# # # #         run: |
# # # #           git pull https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git main || true

# # # #       - name: Commit and Push Changes
# # # #         env:
# # # #           PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
# # # #         run: |
# # # #           git add .github/workflows/manifest1.yml
# # # #           git commit -m "Update workflow files from central template" || echo "No changes to commit"
# # # #           git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"


# # # name: Update Workflows

# # # on:
# # #   repository_dispatch:
# # #     types: [update_workflows]

# # # permissions:
# # #   contents: write
# # #   actions: write

# # # jobs:
# # #   update:
# # #     runs-on: ubuntu-latest

# # #     steps:
# # #       - name: Checkout code
# # #         uses: actions/checkout@v2

# # #       - name: Fetch Central Template
# # #         run: |
# # #           curl -O https://raw.githubusercontent.com/American-Institutes-for-Research/central-workflows/main/.github/workflows/template.yml

# # #       - name: Update Workflow Files
# # #         run: |
# # #           mkdir -p .github/workflows
# # #           cp template.yml .github/workflows/manifest1.yml
# # #           rm template.yml

# # #       - name: Configure Git
# # #         run: |
# # #           git config --global user.name "github-actions[bot]"
# # #           git config --global user.email "github-actions[bot]@users.noreply.github.com"

# # #       - name: Pull Latest Changes
# # #         run: |
# # #           git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main || true

# # #       - name: Commit and Push Changes
# # #         run: |
# # #           git add .github/workflows/manifest1.yml
# # #           git commit -m "Update workflow files from central template" || echo "No changes to commit"
# # #           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"


# # name: Update Workflows

# # on:
# #   repository_dispatch:
# #     types: [update_workflows]

# # permissions:
# #   contents: write  # This allows the workflow to create, read, and write to the repository content
# #   actions: write   # This allows the workflow to create and update GitHub Actions workflows

# # jobs:
# #   update:
# #     runs-on: ubuntu-latest

# #     steps:
# #       - name: Checkout code
# #         uses: actions/checkout@v2

# #       - name: Fetch Central Template
# #         run: |
# #           curl -O https://raw.githubusercontent.com/American-Institutes-for-Research/central-workflows/main/.github/workflows/template.yml

# #       - name: Update Workflow Files
# #         run: |
# #           mkdir -p .github/workflows
# #           cp template.yml .github/workflows/manifest1.yml
# #           rm template.yml

# #       - name: Configure Git
# #         run: |
# #           git config --global user.name "github-actions[bot]"
# #           git config --global user.email "github-actions[bot]@users.noreply.github.com"

# #       - name: Pull Latest Changes
# #         run: |
# #           git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main || true

# #       - name: Commit and Push Changes
# #         run: |
# #           git add .github/workflows/manifest1.yml
# #           git commit -m "Update workflow files from central template" || echo "No changes to commit"
# #           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"


# name: Update Workflows

# on:
#   repository_dispatch:
#     types: [update_workflows]

# permissions:
#   contents: write  # This allows the workflow to create, read, and write to the repository content
#   actions: write   # This allows the workflow to create and update GitHub Actions workflows

# jobs:
#   update:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Fetch Central Template
#         run: |
#           curl -O https://raw.githubusercontent.com/American-Institutes-for-Research/central-workflows/main/.github/workflows/template.yml

#       - name: Update Workflow Files
#         run: |
#           mkdir -p .github/workflows
#           cp template.yml .github/workflows/manifest1.yml
#           rm template.yml

#       - name: Configure Git
#         run: |
#           git config --global user.name "github-actions[bot]"
#           git config --global user.email "github-actions[bot]@users.noreply.github.com"

#       - name: Commit and Push Changes
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git add .github/workflows/manifest1.yml
#           git commit -m "Update workflow files from central template" || echo "No changes to commit"
#           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"

name: Update Workflows

on:
  repository_dispatch:
    types: [update_workflows]

permissions:
  contents: write  # Ensure the workflow has write access to the repository contents
  actions: write   # Ensure the workflow has write access to GitHub Actions workflows

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Central Template
        run: |
          curl -O https://raw.githubusercontent.com/simehta7/repo1/main/.github/workflows/template.yml

      - name: Update Workflow Files
        run: |
          mkdir -p .github/workflows
          cp template.yml .github/workflows/manifest1.yml
          rm template.yml

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .github/workflows/manifest1.yml
          git commit -m "Update workflow files from central template" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"
